---
name: Build

on:
  pull_request:
  push:
    branches:
      - master
  # schedule:
  #   - cron: "10 2 * * 0"

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Test building image.
        run: docker build -t docker-centos7-init .

      - name: Run the built image.
        run: docker run --name container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:rw docker-centos7-init

      - name: Verify systemd is active on container.
        run: docker exec container systemctl status

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ github.repository }}:latest
